### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rogersmykenzie** [KeenanRileyFaulkner/making-decisions-pt-2#1]
Typically try to use `===` for strict equality, which is recommended 99% of the time

https://github.com/KeenanRileyFaulkner/making-decisions-pt-2/blob/de18004d8b31c779e341c26aa473bfa986b4f7f6/makingDecisions2Lab.js#L51

<hr />

Remember you can have a `default` case to handle the "If the letter grade is not one of the above letters, console.log 'Not an eligible grade.'" requirement

https://github.com/KeenanRileyFaulkner/making-decisions-pt-2/blob/de18004d8b31c779e341c26aa473bfa986b4f7f6/makingDecisions2Lab.js#L155-L176

Great job!

**Comment by KeenanRileyFaulkner** [comment]
Thanks for the help! I fixed both issues.
